version: "3"
services:
  comments:
    image: pieca/comments-api:0.0.1
    ports:
      - 8080:8080
    environment:
      - DB_ADDRESS=jdbc:postgresql://postgres:5432/comments
      - DB_USER=comments
      - DB_PASS=comments
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=comments
      - POSTGRES_USER=comments
      - POSTGRES_PASSWORD=comments
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "comments"]
      interval: 10s
      timeout: 10s
      retries: 3
